package ui;

import conexion.REST_UsuariosClient;
import javax.swing.JOptionPane;
import usuarios.Usuario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro Galindo
 */
public class PnlUsuario extends javax.swing.JPanel {

    private Main parent;

    private REST_UsuariosClient cliente;

    private Usuario usuarioBuscado;

    /**
     * Creates new form PnlUsuario
     */
    public PnlUsuario(Main parent, REST_UsuariosClient cliente) {
        initComponents();
        this.parent = parent;
        this.cliente = cliente;
        this.setSize(349, 526);
        tcontrasenia.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tcorreo = new javax.swing.JTextField();
        ttelefono = new javax.swing.JTextField();
        tedad = new javax.swing.JTextField();
        tapellidos = new javax.swing.JTextField();
        tnombre = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        tagregar = new javax.swing.JButton();
        teditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tbuscar = new javax.swing.JTextField();
        teliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnbuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ttipo = new javax.swing.JComboBox<>();
        tcontrasenia = new javax.swing.JPasswordField();
        bLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tcorreo.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N

        ttelefono.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N

        tedad.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N

        tapellidos.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N

        tnombre.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N

        tid.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N

        tagregar.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        tagregar.setText("AGREGAR");
        tagregar.setMaximumSize(new java.awt.Dimension(80, 23));
        tagregar.setMinimumSize(new java.awt.Dimension(80, 23));
        tagregar.setPreferredSize(new java.awt.Dimension(80, 23));
        tagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagregarActionPerformed(evt);
            }
        });

        teditar.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        teditar.setText("EDITAR");
        teditar.setMaximumSize(new java.awt.Dimension(80, 23));
        teditar.setMinimumSize(new java.awt.Dimension(80, 23));
        teditar.setPreferredSize(new java.awt.Dimension(80, 23));
        teditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teditarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel1.setText("Sistema de Gestión de Usuarios de la Mina");

        tbuscar.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N

        teliminar.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        teliminar.setText("ELIMINAR");
        teliminar.setMaximumSize(new java.awt.Dimension(80, 23));
        teliminar.setMinimumSize(new java.awt.Dimension(80, 23));
        teliminar.setPreferredSize(new java.awt.Dimension(80, 23));
        teliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lato", 1, 10)); // NOI18N
        jLabel2.setText("ID Usuario");

        btnbuscar.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        jLabel3.setText("ID:");

        jLabel11.setFont(new java.awt.Font("Lato", 1, 10)); // NOI18N
        jLabel11.setText("Usuario:");

        jLabel4.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        jLabel4.setText("Tipo:");

        jLabel5.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        jLabel6.setText("Apellidos:");

        jLabel7.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        jLabel7.setText("Edad:");

        jLabel8.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        jLabel8.setText("Telefono:");

        jLabel9.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        jLabel9.setText("Correo:");

        jLabel10.setFont(new java.awt.Font("Lato", 0, 10)); // NOI18N
        jLabel10.setText("Contraseña:");

        ttipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GERENCIAL", "OPERADOR" }));
        ttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttipoActionPerformed(evt);
            }
        });

        bLimpiar.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        bLimpiar.setText("LIMPIAR");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tagregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(teditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(teliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(tbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bLimpiar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(19, 19, 19))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tid, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addComponent(tnombre)
                                .addComponent(tapellidos)
                                .addComponent(tedad)
                                .addComponent(ttelefono)
                                .addComponent(tcorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ttipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tcontrasenia, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(jLabel1))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(bLimpiar))
                    .addComponent(tbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tcontrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagregarActionPerformed
        try {
            Usuario usuarioNuevo
                    = new Usuario(ttipo.getSelectedItem().toString(),
                            tnombre.getText(),
                            tapellidos.getText(),
                            Integer.valueOf(tedad.getText()),
                            ttelefono.getText(),
                            tcorreo.getText(),
                            tcontrasenia.getText());

            System.out.println(usuarioNuevo);

            boolean crear = cliente.crearUsuario(usuarioNuevo);

            if (crear) {
                JOptionPane.showMessageDialog(parent, "Usuario creado con exito", "RESULTADO", JOptionPane.INFORMATION_MESSAGE);
                ttipo.setSelectedIndex(0);
                tnombre.setText("");
                tapellidos.setText("");
                tedad.setText("");
                ttelefono.setText("");
                tcorreo.setText("");
                tcontrasenia.setText("");
            } else {
                JOptionPane.showMessageDialog(parent, "Error. Usuario no creado", "RESULTADO", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(parent, "El campo de edad tiene que tener un numero entero", "Error de conversion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tagregarActionPerformed

    private void teditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teditarActionPerformed
        if (usuarioBuscado != null) {
            int input = JOptionPane.showConfirmDialog(parent, "¿Estás seguro que deseas editar al usuario con ID " + usuarioBuscado.getIDUsuario() + "?", "CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);

            if (input == JOptionPane.YES_OPTION) {
                try {
                    usuarioBuscado.setTipo(ttipo.getSelectedItem().toString());
                    usuarioBuscado.setNombre(tnombre.getText());
                    usuarioBuscado.setApellidos(tapellidos.getText());
                    usuarioBuscado.setEdad(Integer.valueOf(tedad.getText()));
                    usuarioBuscado.setTelefono(ttelefono.getText());

                    System.out.println(usuarioBuscado);

                    boolean editar = cliente.editarUsuario(usuarioBuscado);

                    if (editar) {
                        JOptionPane.showMessageDialog(parent, "Usuario editado con exito", "RESULTADO", JOptionPane.INFORMATION_MESSAGE);
                        tid.setText("");
                        ttipo.setSelectedIndex(0);
                        tnombre.setText("");
                        tapellidos.setText("");
                        tedad.setText("");
                        ttelefono.setText("");
                        tcorreo.setText("");
                        tcorreo.setEnabled(true);
                        tcontrasenia.setText("");
                        tcontrasenia.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(parent, "Error. Usuario no editado", "RESULTADO", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (NumberFormatException numberFormatException) {
                    JOptionPane.showMessageDialog(parent, "El campo de edad tiene que tener un numero entero", "Error de conversion", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(parent, "Busca un usuario", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_teditarActionPerformed

    private void teliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teliminarActionPerformed
        if (usuarioBuscado != null) {
            int input = JOptionPane.showConfirmDialog(parent, "¿Estás seguro que deseas eliminar al usuario con ID " + usuarioBuscado.getIDUsuario() + "?", "CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);

            if (input == JOptionPane.YES_OPTION) {

                boolean eliminar = cliente.eliminarUsuario(usuarioBuscado);

                if (eliminar) {
                    JOptionPane.showMessageDialog(parent, "Usuario eliminado con exito", "RESULTADO", JOptionPane.INFORMATION_MESSAGE);
                    tid.setText("");
                    ttipo.setSelectedIndex(0);
                    tnombre.setText("");
                    tapellidos.setText("");
                    tedad.setText("");
                    ttelefono.setText("");
                    tcorreo.setText("");
                    tcorreo.setEnabled(true);
                    tcontrasenia.setText("");
                    tcontrasenia.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(parent, "Error. Usuario no eliminado", "RESULTADO", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(parent, "Busca un usuario", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_teliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try {
            //nomás pa ver si es numero, no se va a usar en número, como tal
            Integer.valueOf(tbuscar.getText());

            Usuario usuario = cliente.obtenerUsuario(tbuscar.getText());
            this.usuarioBuscado = usuario;

            if (usuario != null) {
                tid.setText(String.valueOf(usuario.getIDUsuario()));
                tid.setEnabled(false);
                ttipo.setSelectedIndex(0);
                tnombre.setText(usuario.getNombre());
                tapellidos.setText(usuario.getApellidos());
                tedad.setText(String.valueOf(usuario.getEdad()));
                ttelefono.setText(usuario.getTelefono());
                tcorreo.setText(usuario.getCorreoElectronico());
                tcorreo.setEnabled(false);
                tcontrasenia.setText("");
                tcontrasenia.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(parent, "No se ha encontrado a un usuario con el ID indicado", "SIN RESPUESTA", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(parent, "El ID a buscar tiene que ser númerico", "Error de conversion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        tid.setText("");
        ttipo.setSelectedIndex(0);
        tnombre.setText("");
        tapellidos.setText("");
        tedad.setText("");
        ttelefono.setText("");
        tcorreo.setText("");
        tcorreo.setEnabled(true);
        tcontrasenia.setText("");
        tcontrasenia.setEnabled(true);
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void ttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton tagregar;
    private javax.swing.JTextField tapellidos;
    private javax.swing.JTextField tbuscar;
    private javax.swing.JPasswordField tcontrasenia;
    private javax.swing.JTextField tcorreo;
    private javax.swing.JTextField tedad;
    private javax.swing.JButton teditar;
    private javax.swing.JButton teliminar;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tnombre;
    private javax.swing.JTextField ttelefono;
    private javax.swing.JComboBox<String> ttipo;
    // End of variables declaration//GEN-END:variables
}
